---
title: "Having a Ball: evaluating game excitement and scoring streaks using in-match trend estimation"
author: | 
  | Claus Thorn Ekstrøm and Andreas Kryger Jensen
  | Biostatistics, Institute of Public Health, University of Copenhagen
  | ekstrom@sund.ku.dk, aeje@sund.ku.dk
date: "`r format(Sys.time(), '%d %B, %Y')`"
fontsize: 11pt  
header-includes:
  - \usepackage{bm}
  - \usepackage{amssymb}
  - \usepackage[labelfont=bf]{caption}
  - \DeclareMathOperator*{\argsup}{arg\,sup}  
  - \DeclareMathOperator*{\argmin}{arg\,min}  
  - \DeclareMathOperator*{\E}{E}
  - \DeclareMathOperator*{\Cov}{Cov}
  - \DeclareMathOperator*{\Cor}{Cor}
  - \DeclareMathOperator*{\Var}{Var}
  - \DeclareMathOperator*{\Erf}{Erf}
  - \DeclareMathOperator*{\Erfc}{Erfc}
  - \usepackage{multirow}
  - \usepackage{float}
  - \floatstyle{plaintop}
  - \restylefloat{table}
  - \usepackage[amsthm,thmmarks]{ntheorem}
  - \newtheorem{definition}{Definition}
  - \newtheorem{assumption}{Assumption}
  - \newtheorem{proposition}{Proposition}
  - \theoremstyle{nonumberplain}
  - \newtheorem{Proof}{Proof}
  - \usepackage{xcolor}
  - \newcommand{\revision}[1]{\textcolor{red}{#1}}
output:
  pdf_document: 
    keep_tex: yes
    number_sections: yes
editor_options: 
  chunk_output_type: console
---

\begin{abstract}
Nu ved jeg godt nok intet om sport, men...
\end{abstract}

\begin{center}
\textbf{Keywords:} Sports statistics, Gaussian Processes, Trends, Bayesian Statistics
\end{center}

# Introduction

We introduce the Execitement Trend Index (ETI) as an objective measure of spectator exicitement in a given match.

\begin{itemize}
\item Excitement defineret som skift af hvem, der er i føring
\item Vurdering af om et hold trender lige pt.
\item Identificere hvilket ``hot periods'' et hold har i løbet af en kamp til efterfølgende evaluering
\end{itemize}

Ref til trends

Needs a reference and some kind of comparison to "Rank dynamics for functional data" by Chen, Dawson and Müller, Computational Statistics and Data Analysis, 149, 2020.

Vi kan overveje, om vi ikke udelukkende burde fokusere på Eddy i dette manus og foreslå dette som et objektivt excitement index i stedet for at gå ind i en diskussion om TDI også.

# Methods {#sec:method}
Let $m$ index a given match between teams $a$ and $b$ and let $D_m(t_{m_i}) = S_a(t_{m_i}) - S_{b}(t_{m_i})$ be the difference in scores at times $t_{m_1} < t_{m_2} < t_{m_i} < \ldots$ being the ordered event times when a score by either team $a$ or $b$ occurs  during match $m$.

We then look at the model
\begin{align*}
  \Theta_m &\sim F_m\\
  f_m(t) \mid \Theta_m &\sim \mathcal{GP}(\mu_{\beta_m}, C_{\theta_m})\\
  D_m(t_{m_i}) \mid f_m(t_{m_i}), t_{m_i}, \Theta_m &\overset{iid}{\sim} N(f_m(t_{m_i}), \sigma_{m}^2)
\end{align*}
where $\Theta_m = (\beta_m, \theta_m, \sigma_{m}^2)$ and $f_m$ is a latent (?, proper name) trajectory of score differences.


\begin{itemize}
\item Trenderen
\item TDI
\item Excitement Trend Index
\end{itemize}

We need to argue that $S_a(t_{m_i}) - S_{b}(t_{m_i})$ is symmetric in $a$ and $b$ so that our choice of "reference group" is arbitrary/not important.

# Results {#sec:application}

\begin{itemize}
\item 
\end{itemize}


# Discussion {#sec:discussion}

We could define a weighted Excitement Trend Index wETI, so that zero crossings of the derivative of score differences are weighted higher towards the end of the game as in 
\begin{align*}
  \mathrm{wETI} = \int_{0}^{48} w(t)d \mathrm{ETI}(t)
\end{align*}
where $w(t)$ is then an increasing weight function.


# Acknowledgements {-}

# Bibliography {-}

<div id="refs"></div>

