---
title: |
  | Supplementary Material
  | Having a Ball: evaluating scoring streaks and game excitement using in-match trend estimation
author: | 
  | Claus Thorn Ekstrøm and Andreas Kryger Jensen
  | Biostatistics, Institute of Public Health, University of Copenhagen
  | ekstrom@sund.ku.dk, aeje@sund.ku.dk
date: "`r format(Sys.time(), '%d %B, %Y')`"
fontsize: 11pt  
output: pdf_document
---

```{r, echo=FALSE}
rm(list=ls())
load("../analysis/est_ETIs.RData")
load("../data/nba20192020.rda")

ETIs$date <- as.Date(sapply(results, function(q) attributes(q)$date), format="%B %e, %Y")
ETIs$home <- as.factor(sapply(results, function(q) attributes(q)$home))
ETIs$away <- as.factor(sapply(results, function(q) attributes(q)$away))
```

# Median posterior excitement per team across season
```{r, echo=FALSE}
# Get team-specific average ETIs during season
team_averages <- rbind(data.frame(Team = ETIs$home, ETI = ETIs$median),
                       data.frame(Team = ETIs$away, ETI = ETIs$median))
team_summary <- t(sapply(split(team_averages, team_averages$Team), function(q) {
  c(Average = mean(q$ETI), SD = sd(q$ETI), quantile(q$ETI, 0.025), quantile(q$ETI, 0.5), quantile(q$ETI, 0.975))
}))
team_summary <- round(as.data.frame(team_summary), 2)
team_summary$Team <- rownames(team_summary)

tab <- team_summary[order(team_summary[,"Average"], decreasing=TRUE),]
knitr::kable(tab[,c("Team", "Average", "SD", "2.5%", "50%", "97.5%")], row.names=FALSE)
```

# Games ordered by decreasing average excitement
```{r, echo=FALSE}
library(kableExtra)
dat <- ETIs[order(ETIs$mean, decreasing=TRUE),]
res1 <- dat[, c("date", "home", "away", "mean", "lower", "median", "upper")]
colnames(res1) <- c("Date", "Home team", "Away team", "Mean ETI", "2.5% ETI", "50% ETI", "97.5% ETI")
rownames(res1) <- NULL
knitr::kable(res1, digits=2, booktabs = TRUE, format="latex", longtable=TRUE, linesep = c("", "", "", ""),  align =c("l|", "l", "l|", "r", "r", "r", "r")) %>%
  kable_styling(latex_options = c("hold_position", "repeat_header")) %>% 
  kable_styling(font_size = 8)
```

