---
title: "basketball"
date: "11/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
url <- "https://www.basketball-reference.com/boxscores/pbp/202010090LAL.html"
library("rvest")
library("tidyverse")

raw_data <- 
    url %>% 
    read_html() %>% 
    html_table() %>% 
    as.data.frame()

names(raw_data) <- c("time", "text", "change", "score", "change2", "text2")
```


## Heavy wrangling

Need to fix times and scores

First we try to fix time
```{r}
   val1 <- as.numeric(raw_data$change) 
   val2 <- as.numeric(raw_data$change2)
   
   keeptimes <- ((!is.na(val1)) | (!is.na(val2)))
   
   scorediff <- cumsum(ifelse(is.na(val1), 0, val1)) - cumsum(ifelse(is.na(val2), 0, val2))
   
   scorediff <- scorediff[keeptimes]

   
  splitl <- stringr::str_split(raw_data$time, ":")
   for (i in 1:length(splitl)) {
       splitl[[i]]
   }


   part1 <- sapply(stringr::str_split(raw_data$time, ":"), function(i) {
       ifelse(length(i)==1, NA, 12-as.numeric(i[1]) -
              as.numeric(stringr::str_split(i[2], "\\.")[[1]][1])/60 -
              as.numeric(stringr::str_split(i[2], "\\.")[[1]][2])/60/100
       )
   })
   
   # Now convert quarters
   quarter <- 0
   part2 <- part1
   for (i in 1:length(part1)) {
       if (!is.na(part2[i]) & part2[i]==0) {
           quarter <- quarter +1
       }
       part2[i] <- part1[i]+12*(quarter-1)
   }

  part1 <- part1[keeptimes]
   

  DF <- data.frame(time=part2[keeptimes], scorediff)
  DF
```


```{r}
library(DEoptim)
library(mvtnorm)
library(rstan)

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

tPred <- seq(min(DF$time), max(DF$time), length.out = 200)

########################################################
# Estimate Empirical Bayes parameters
########################################################
rqCov <- function(s, t, alpha, rho, nu) {
  alpha^2 * (1 + (s-t)^2 / (2 * nu * rho^2))^(-nu)
}

ctl <- DEoptim.control(itermax = 1000, trace = 100)
set.seed(1234)
opt.rq <- DEoptim(function(par) {
  mu <- rep(par[1], nrow(DF))
  cMat <- outer(DF$time, DF$time, rqCov, par[2], par[3], 10000) + diag(par[4]^2 , nrow(DF))
  -mvtnorm::dmvnorm(DF$scorediff, mu, cMat, log=TRUE)
}, lower = c(0,0,0,0), upper = c(50,50,50,50), control = ctl)
par.rq <- opt.rq$optim$bestmem
par.rq
```

```{r}
sDat <- list(n = nrow(DF), t = DF$time, y = DF$scorediff, p = length(tPred), tPred = tPred)
sDat$mu <- par.rq[1]
sDat$alpha <- par.rq[2]
sDat$rho <- par.rq[3]
sDat$nu <- 10000
sDat$sigma <- par.rq[4]

iter <- 10000
seed <- 12345
m <- stan_model("gptrendFixed.stan")
fit <- sampling(m, data = sDat, iter = iter, seed = seed, algorithm = "Fixed_param")
pred <- extract(fit, "pred")$pred
```


```{r}
band <- function(t, l, u, col) {
  polygon(c(t, rev(t)), c(l, rev(u)), col=col, border = NA)
}

pdf("../figures/gpFit.pdf", width = 8, height = 6)

par(mfrow=c(2,2), bty="n", mar = c(2.3, 2.3, 1, 0), mgp=c(1.3,0.4,0))
plot(DF$time, DF$scorediff, pch = 19, xlab="Game time", ylab="f | Y", type="n", ylim=c(-12, 12), xlim=c(0,50), yaxt="n")
axis(2, seq(-12, 12, length.out=7))
band(tPred, apply(pred[,,1], 2, quantile, prob = 0.005), apply(pred[,,1], 2, quantile, prob = 0.995), col = "gray80")
band(tPred, apply(pred[,,1], 2, quantile, prob = 0.025), apply(pred[,,1], 2, quantile, prob = 0.975), col = "gray65")
band(tPred, apply(pred[,,1], 2, quantile, prob = 0.25), apply(pred[,,1], 2, quantile, prob = 0.75), col = "gray45")
lines(tPred, apply(pred[,,1], 2, mean), lwd = 2)
points(DF$time, DF$scorediff, pch = 19, cex=0.8)
abline(h = 0, lty=2)
legend("topleft", c("Mean", "50%", "95%", "99%"), col = c("black", "gray45", "gray65", "gray85"), 
       lwd = 2, bty="n", cex=0.7, lty = c(1, NA, NA, NA), pch = c(NA, 15, 15, 15), pt.cex=1.5)

plot(tPred, apply(pred[,,3], 2, mean), lwd = 2, type="n", ylim = c(-10, 10), xlab="Game time", ylab="df | Y", xlim=c(0,50))
band(tPred, apply(pred[,,3], 2, quantile, prob = 0.005), apply(pred[,,3], 2, quantile, prob = 0.995), col = "gray80")
band(tPred, apply(pred[,,3], 2, quantile, prob = 0.025), apply(pred[,,3], 2, quantile, prob = 0.975), col = "gray65")
band(tPred, apply(pred[,,3], 2, quantile, prob = 0.25), apply(pred[,,3], 2, quantile, prob = 0.75), col = "gray45")
lines(tPred, apply(pred[,,3], 2, mean), lwd = 2)
abline(h = 0, lty = 2)
legend("topleft", c("Mean", "50%", "95%", "99%"), col = c("black", "gray45", "gray65", "gray85"), 
       lwd = 2, bty="n", cex=0.7, lty = c(1, NA, NA, NA), pch = c(NA, 15, 15, 15), pt.cex=1.5)

plot(tPred, t(pred[1,,5])*100, type="l", lty = 1, lwd = 2, xlab="Game time", 
     ylab="Trend Direction Index [%]", ylim=c(0,100), xlim=c(0,50))
abline(h = 50, lty = 2)
title("Trend Direction Index", font.main=1)

plot(tPred, t(pred[1,,6]), type="l", lty = 1, lwd = 2, xlab="Game time", 
     ylab="dETI", ylim=c(0,2.5), xlim=c(0,50))
title("Local Excitement Trend Index", font.main=1)

dev.off()
```

```{r}
integrate(splinefun(tPred, pred[1,,6]), min(tPred), max(tPred))
```

